# Generated by Django 4.2.13 on 2024-05-29 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_collaboraterequest'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CollaborateRequest',
            new_name='ContactRequest',
        ),
    ]
