# Generated by Django 4.2.13 on 2024-06-03 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_post_email_post_nationality_post_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='languages_spoken',
            new_name='Languages',
        ),
    ]
