# Generated by Django 4.2.13 on 2024-06-03 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_rename_languages_spoken_post_languages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Languages',
        ),
        migrations.AddField(
            model_name='post',
            name='language',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Language',
        ),
    ]
