# Generated by Django 4.2.13 on 2024-06-03 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_remove_post_languages_post_language_delete_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='language',
            new_name='languages_spoken',
        ),
    ]
