# Generated by Django 4.2.13 on 2024-06-04 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_rename_language_post_languages_spoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='languages_spoken',
        ),
    ]
